apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-web-app
  namespace: web-app
spec:
  selector:
    matchLabels:
      app: tg-web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: tg-web-app
    spec:
      containers:
        - name: tg-web-app
          image: dopeteam/tg-web-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-log
              mountPath: /var/log/nginx
      volumes:
        - name: nginx-log
          emptyDir: {}
