name: Production Workflow for TG Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    uses: d-o-p-e/ci-cd/.github/workflows/react.yaml@main
    with:
      NODE_VERSION: 16
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}