name: Production Workflow for TG Web App

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
jobs:
  if_merged:
    name: Check for valid push record.
#     if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR was merged, or Activated manually.
        run: |
          echo "VALID CONDITION. START DEPLOYMENT."
  build-and-deploy:
    needs: if_merged
    uses: d-o-p-e/ci-cd/.github/workflows/react.yaml@main
    with:
      NODE_VERSION: 16
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
