name: Production Workflow for TG Web App

on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  if_merged:
    name: Check if the pull request was merged
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - name: Check if PR was merged.
        run: |
          echo "PR WAS MERGED TO PRODUCTION. START DEPLOYMENT."
  build-and-deploy:
    needs: if_merged
    uses: d-o-p-e/ci-cd/.github/workflows/react.yaml@main
    with:
      NODE_VERSION: 16
    secrets:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
